# Deploy ADF self-hosted to UAT environment. I have a shared SHIR.

name: ADF1 SHIR Workspace Deployment 

on:
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'Resource group name'
        default: 'rg-adf-self-hosted-destination'
        required: true 

jobs:
  deploy-to-uat:
    name: Deploy to UAT 
    runs-on: ubuntu-latest
  
  steps:
    - name: Login to Azure
      uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Checkout
      uses: actions/checkout@v3

    - name: ADF UAT Deploy 
    uses: Azure/data-factory-deploy-action@v1.2.0
    with: 
      resourceGroupName: ${{ github.event.inputs.resourceGroup }}
      dataFactoryName: adf-self-hosted-uat
      skipAzModuleInstallation: true 
      
    





    


